### ISSUE TITLE
Porting to Linux

### ISSUE THREAD

**Issue by hubshi** [brianrho/fpmatch#1]
Thank you for this wonderful piece of software, is it possible to port it to Linux ? or most likely ARM based Linux just like Raspberry Pi or other SBCs, 

Best Regards

**Comment by brianrho** [comment]
You're welcome. I did consider creating a Linux version since it'll likely be the most used OS for this application, but I was unable to find a corresponding .so library in the SDK or elsewhere online  and it seems there's no way to convert a .dll to .so or something that can be used with Linux. Only options left I can see are to decompile the DLL maybe and try to deduce the matching logic, or to use the DLL with Wine

**Comment by hubshi** [comment]
Thank you for your reply, I am looking forward to it.

Best Regards

**Comment by brianrho** [comment]
I'm afraid that likely won't be coming anytime soon, I took a stab at the DLL de-compilation recently with [this](https://derevenets.com/) and got nowhere with the resulting C++, the matching function is too obfuscated, either naturally by the nature of de-compiled code or intentionally by the manufacturer. You're welcome to try it yourself or use Wine, starting [here](https://linux.die.net/man/1/winedump) maybe

**Comment by hubshi** [comment]
Thank you for our suggestion ,but I am more interested in ARM based Linux SBCs while wine can only help while DLL is of x86 arch.

**Comment by abhibhatia98** [comment]
Hi @hubshi, have you tried some thing on this ? Actually I am too working on the similar use case, integrating fingerprint sensor with pi  for more then 1000 prints , posted on [forum](https://arduino.stackexchange.com/questions/81382/r307-fingerprint-sensor-working-with-more-then-1000-fingerprints), please help if you ahve some thing that can help me . TIA
