### ISSUE TITLE
Cloud not Find ARTH_DLL

### ISSUE THREAD

**Issue by rickyanwar** [brianrho/fpmatch#5]
I
![trying](https://user-images.githubusercontent.com/36995966/104848857-30a36080-5919-11eb-8c41-da31f9117e07.png)
 place it in the same folder and using windows to test but ARTH_DLL is missing (Python 3.8)

![c](https://user-images.githubusercontent.com/36995966/104849661-8a0d8e80-591d-11eb-9995-af77ffc34bb9.png)
trying using python 2.7 still eror

**Comment by brianrho** [comment]
Like the README says, make sure your Python is 32-bit: https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit

**Comment by rickyanwar** [comment]
![trying](https://user-images.githubusercontent.com/36995966/104870874-2a929b80-597c-11eb-9138-fae77e689080.png)
trying with python 3.8 32 bit python have same issue,

**Comment by brianrho** [comment]
The function itself is for 1:1 matching, but nothing stops you from iterating through N prints.

I'm not sure what's going on in your environment. I'd suggest you stop using the Mingw/Bash window and instead run this in a proper Powershell window to run the command like so: `py -3.8 fpmatch.py`

It's also possible that your issue is caused by [this](https://stackoverflow.com/questions/59014318/filenotfounderror-could-not-find-module-libvlc-dll), in which case, you can try passing the absolute DLL path to the function:
```
arth = WinDLL(r'<DLL absolute path>')
```
...and see if that works.

**Comment by brianrho** [comment]
I assumed that solved your issue.
